# Generated by Django 4.2.13 on 2025-06-30 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=100)),
                ('passage', models.CharField(max_length=100)),
                ('audio_data', models.BinaryField()),
                ('audio_name', models.CharField(max_length=255)),
                ('audio_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(default='audio/mpeg', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
