# Generated by Django 4.2.13 on 2025-07-02 01:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosermon',
            name='audio_data',
        ),
        migrations.AddField(
            model_name='audiosermon',
            name='audio_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='audiosermon',
            name='total_chunks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audiosermon',
            name='audio_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='audiosermon',
            name='audio_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AudioUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('audio_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('total_size', models.PositiveIntegerField()),
                ('uploaded_size', models.PositiveIntegerField(default=0)),
                ('total_chunks_expected', models.PositiveIntegerField()),
                ('chunks_received', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('sermon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='sermons.audiosermon')),
            ],
        ),
        migrations.CreateModel(
            name='AudioUploadChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_order', models.PositiveIntegerField()),
                ('data', models.BinaryField()),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_chunks', to='sermons.audiouploadsession')),
            ],
            options={
                'ordering': ['chunk_order'],
                'unique_together': {('session', 'chunk_order')},
            },
        ),
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_order', models.PositiveIntegerField()),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sermons.audiosermon')),
            ],
            options={
                'ordering': ['chunk_order'],
                'unique_together': {('sermon', 'chunk_order')},
            },
        ),
    ]
