# Generated by Django 4.2.13 on 2025-06-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('body', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('pdf_data', models.BinaryField()),
                ('pdf_name', models.CharField(max_length=255)),
                ('pdf_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
